export {
  DFLT_SALES_PLATFORM_SUPPORT_CONTACT as DFLT_INTEGRATION_SUPPORT_CONTACT,
  SUPPORT_CONTACT_CARD_FIELDS,
  SUPPORT_CONTACT_CARD_PREVIEW_FIELDS,
  SUPPORT_CONTACT_COPYABLE_CARD_FIELDS,
  SUPPORT_CONTACT_LINK_FIELDS,
  formatSupportContactDisplayValue,
  getSupportContactFieldValue,
  getSupportContactCardTitle,
  cloneSupportContact,
  duplicateSupportContact,
  copySupportContactText,
  seedSupportContactsFromPlatform as seedSupportContactsFromIntegration,
  getSupportContactFieldHref,
  SUPPORT_CONTACTS_PER_ROW,
  SUPPORT_CONTACTS_SLOTS_PER_ROW,
  formatSupportContactTotalLabel,
  buildSupportContactGridRows,
  getSupportContactGridMeta,
} from "./salesPlatformSupportContacts_hlpr.js";
