cK_menuItem_addModifiers
cK_menuItem_removeModifiers
cK_menuItem_reorderModifiers
cK_menuItem_addMirrors
cK_menuItem_removeMirrors
cK_menuItem_addCompetes
cK_menuItem_removeCompetes




cK_menuItem_addModifiers
cK_menuItem_removeModifiers
cK_menuItem_reorderModifiers
cK_menuItem_addMirrors
cK_menuItem_removeMirrors
cK_menuItem_addCompetes
cK_menuItem_removeCompetes
