
cK_menuItem_update_ownerType
cK_menuItem_update_ownerId
cK_menuItem_update_name
cK_menuItem_update_cost
cK_menuItem_update_description
cK_menuItem_update_sellingPrice
cK_menuItem_update_cuisineType
cK_menuItem_update_images
cK_menuItem_update_recipe
cK_menuItem_update_recipeFile
cK_menuItem_update_techCardFile
cK_menuItem_update_otherFiles
cK_menuItem_update_priceHistory
cK_menuItem_update_sizeByGrams
cK_menuItem_update_quantity
cK_menuItem_update_dietaryTags
cK_menuItem_update_allergens
cK_menuItem_update_spicyLevel
cK_menuItem_update_preparationTimeMin
cK_menuItem_update_sku
cK_menuItem_update_kitchenStation
cK_menuItem_update_nutrition
cK_menuItem_update_source
cK_menuItem_update_externalId
cK_menuItem_update_cloudStorage




cK_menuItem_update_ownerType
cK_menuItem_update_ownerId
cK_menuItem_update_name
cK_menuItem_update_cost
cK_menuItem_update_description
cK_menuItem_update_sellingPrice
cK_menuItem_update_cuisineType
cK_menuItem_update_images
cK_menuItem_update_recipe
cK_menuItem_update_recipeFile
cK_menuItem_update_techCardFile
cK_menuItem_update_otherFiles
cK_menuItem_update_priceHistory
cK_menuItem_update_sizeByGrams
cK_menuItem_update_quantity
cK_menuItem_update_dietaryTags
cK_menuItem_update_allergens
cK_menuItem_update_spicyLevel
cK_menuItem_update_preparationTimeMin
cK_menuItem_update_sku
cK_menuItem_update_kitchenStation
cK_menuItem_update_nutrition
cK_menuItem_update_source
cK_menuItem_update_externalId
cK_menuItem_update_cloudStorage