version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - cd backEnd
      - npm ci --production
artifacts:
  base-directory: backEnd
  files:
    - '**/*'
