/*
Brands_table_rows_names
Brands_table_rows_logos
Brands_table_rows_branches
Brands_table_rows_employees
Brands_table_rows_emquipments
Brands_table_rows_menus
Brands_table_rows_competitors

brands_table_rows_names
brands_table_rows_logos
brands_table_rows_branches
brands_table_rows_employees
brands_table_rows_emquipments
brands_table_rows_menus
brands_table_rows_competitors



Brands_view_all
Brands_view_bySection_names
Brands_view_bySection_logos
Brands_view_bySection_branches
Brands_view_bySection_employees
Brands_view_bySection_emquipments
Brands_view_bySection_menus
Brands_view_bySection_competitors


Brands_view_all
Brands_view_bySection_names
Brands_view_bySection_logos
Brands_view_bySection_branches
Brands_view_bySection_employees
Brands_view_bySection_emquipments
Brands_view_bySection_menus
Brands_view_bySection_competitors

*/