import {
  // BrandDevelopment_icon,
  // DeliveryCoverage_Icon,
  // OurSupport_Icon,
  // ManagerSupport_Icon,
  // Hours24_Icon,
  // Equipments_Icon,
  // Images_Icon,
  // Files_Icon,
  // MapView_Icon,
  // ListView_Icon,
  // Category_Icon,
  // Area_Icon,
  // City_Icon,
  // Country_Icon,
  // DineIn_Icon,
  // Dish_Icon,
  // Budget_Icon,
  // Medium_Icon,
  // Premium_Icon,
  // PriceRange_Icon,
  // Modifiers_Icon,
  // IsDelivery_Icon,
  // Tags_Icon,
  // Update_Icon,
  // Polygon_Icon,
  // Radius_Icon,
  // Emirate_Icon,
  // Ingredients_Icon,
  // Operations_Icon,
  // Packaging_Icon,
  // Street_Icon,
  // Sup_Recipe_Icon,
  Recipe_Icon,
  Supplier_Icon,
  SalesChannel_Icon,
  Earth_Icon,
  Dashboard_Icon,
  Branches_Icon,
  Competitors_Icon,
  Employees_Icon,
  Brands_Icon,
  FoodMenu_Icon,
} from "../../../../01_components/components.index.js";

const cloudKitchens_SideBar = (t) => [
  {
    label: t("branches") || "Branches",
    path: "cloudKitchens_branches",
    icon: Branches_Icon(),
    access: ["admin", "superAdmin"],
    isDefault: true,
  },
  {
    label: t("brands", { defaultValue: "Brands" }),
    path: "cloudKitchens_brands",
    icon: Brands_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: "Competitors",
    path: "cloudKitchens_competitors",
    icon: Competitors_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: t("employees", { defaultValue: "Employees" }),
    path: "cloudKitchens_employees",
    icon: Employees_Icon(),
    access: ["admin", "superAdmin"],
  },

  {
    label: t("menus", { defaultValue: "Menus" }),
    path: "cloudKitchens_menus",
    icon: FoodMenu_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: t("newMenu", { defaultValue: "NewMenu" }),
    path: "cloudKitchens_newMenu",
    icon: FoodMenu_Icon(),
    access: ["admin", "superAdmin"],
  },

  // ---------------------------------------------
  {
    label: "Recipe_Icon",
    path: "cloudKitchens_XXX",
    icon: Recipe_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: "Earth_Icon",
    path: "cloudKitchens_XXX",
    icon: Earth_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: "Dashboard_Icon",
    path: "cloudKitchens_menuItems",
    icon: Dashboard_Icon(),
    access: ["admin", "superAdmin"],
  },

  {
    label: "SalesChannel Icon",
    path: "cloudKitchens_XXX",
    icon: SalesChannel_Icon(),
    access: ["admin", "superAdmin"],
  },
  {
    label: "Supplier_Icon",
    path: "cloudKitchens_XXX",
    icon: Supplier_Icon(),
    access: ["admin", "superAdmin"],
  },
  // {
  //   label: "Earth_Icon3",
  //   path: "cloudKitchens_XXX",
  //   icon: Earth_Icon3(),
  //   access: ["admin", "superAdmin"],
  // },
];

export default cloudKitchens_SideBar;
