export const DATABASES = [
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "MariaDB",
  "Microsoft SQL Server",
  "Oracle Database",
  "Redis",
  "Apache Cassandra",
  "Elasticsearch",
  "Neo4j",
  "IBM DB2",
  "CouchDB",
  "Amazon DynamoDB",
  "Firebase Firestore",
];

export const CLOUD_STORAGES = [
  "AWS S3",
  "Google Cloud Storage",
  "Azure Blob Storage",
  "Amazon DynamoDB",
  "Google Cloud Firestore",
  "Azure Cosmos DB",
  "Backblaze B2",
  "Oracle Cloud Object Storage",
  "IBM Cloud Object Storage",
  "DigitalOcean Spaces",
  "Cloudflare R2",
  "Wasabi",
  "Dropbox",
  "Google Drive",
  "Microsoft OneDrive",
];

export const FRONTEND_PACKAGES = [
  "react-router-dom",
  "@tanstack/react-query",
  "axios",
  "react-hook-form",
  "zod",
  "@hookform/resolvers",
  "tailwindcss",
  "clsx",
  "tailwind-merge",
  "framer-motion",
  "lucide-react",
  "recharts",
  "react-hot-toast",
  "date-fns",
  "vite",
];

export const BACKEND_PACKAGES = [
  "express",
  "mongoose",
  "dotenv",
  "cors",
  "helmet",
  "morgan",
  "compression",
  "express-rate-limit",
  "jsonwebtoken",
  "bcryptjs",
  "cookie-parser",
  "multer",
  "nodemon",
  "winston",
  "zod",
];

export const TECH_STACKS = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Redux Toolkit",
  "Docker",
  "Git",
  "AWS",
];
