import {
  Brand_add,
  Brand_getAll,
  Brand_getOne,
  Brand_update,
  Brand_delete,
  Brand_getSection,
  Brand_putSection,
  Brand_clearSection,
  Brand_addSectionItem,
  Brand_updateSectionItem,
  Brand_removeSectionItem,
  Brand_linkBranch,
  Brand_unlinkBranch,
  Brand_linkEmployee,
  Brand_unlinkEmployee,
  Brand_setMenu,
  Brand_clearMenu,
  Brand_uploadLogo,
  Brand_getLogo,
  Branch_getAll,
  Employee_getAll,
  Menu_getAll,
} from "../../../../../../05_helpers/apiHelpers/admin/adminFeatures/_adminFeatures.index.js";
import Settings_get from "../../../../../../05_helpers/apiHelpers/admin/adminFeatures/settings/Settings_get.js";

export const useBrands_apiHelpers = () => ({
  apiHelpers: {
    Brand_add,
    Brand_getAll,
    Brand_getOne,
    Brand_update,
    Brand_delete,
    Brand_getSection,
    Brand_putSection,
    Brand_clearSection,
    Brand_addSectionItem,
    Brand_updateSectionItem,
    Brand_removeSectionItem,
    Brand_linkBranch,
    Brand_unlinkBranch,
    Brand_linkEmployee,
    Brand_unlinkEmployee,
    Brand_setMenu,
    Brand_clearMenu,
    Brand_uploadLogo,
    Brand_getLogo,
    Branch_getAll,
    Employee_getAll,
    Menu_getAll,
    Settings_get,
  },
});
