export const GLOBAL_PRIORITIES = [
  {
    id: 10,
    value: "emergency",
    label: "Emergency",
    description: "Immediate action required. Highest possible priority.",
    textColor: "#FFFFFF",
    bgColor: "#D7263D",
  },
  {
    id: 9,
    value: "critical",
    label: "Critical",
    description: "Severe importance. Needs to be resolved as soon as possible.",
    textColor: "#FFFFFF",
    bgColor: "#E63946",
  },
  {
    id: 8,
    value: "urgent",
    label: "Urgent",
    description:
      "Time-sensitive and highly important. Should be handled quickly.",
    textColor: "#FFFFFF",
    bgColor: "#FF6F3C",
  },
  {
    id: 7,
    value: "important",
    label: "Important",
    description:
      "Meaningful impact on progress. Prioritize after urgent tasks.",
    textColor: "#FFFFFF",
    bgColor: "#FFA552",
  },
  {
    id: 6,
    value: "medium",
    label: "Medium",
    description: "Standard priority. No immediate time pressure.",
    textColor: "#000000",
    bgColor: "#FFDD57",
  },
  {
    id: 5,
    value: "below-medium",
    label: "Below Medium",
    description:
      "Not time-sensitive; can wait until higher priorities are cleared.",
    textColor: "#000000",
    bgColor: "#CDE77F",
  },
  {
    id: 4,
    value: "low",
    label: "Low",
    description: "Minor task or small improvement. Not urgent.",
    textColor: "#000000",
    bgColor: "#A1C45A",
  },
  {
    id: 3,
    value: "very-low",
    label: "Very Low",
    description: "Minimal priority. Can be postponed indefinitely.",
    textColor: "#FFFFFF",
    bgColor: "#6A994E",
  },
  {
    id: 2,
    value: "someday",
    label: "Someday",
    description: "Future ideas or tasks with no schedule.",
    textColor: "#FFFFFF",
    bgColor: "#386641",
  },
  {
    id: 1,
    value: "wishlist",
    label: "Wishlist",
    description: "Pure ideas or optional improvements with no commitment.",
    textColor: "#FFFFFF",
    bgColor: "#2A3D34",
  },
];
