export {
  GCS_BUCKET_NAME,
  GCS_APP_CRED_PATH,
  GCP_PROJECT_ID,
  GCS_OBJECT_KEY_PREFIX,
  GCS_MAX_KEY_LEN,
  GCS_EXP_MAX_TIME,
  GCS_EXP_DEFAULT_TIME,
  GCS_EXP_MAX_TIME_HARD_CAP,
} from "./gcs_config.js";
